name: Build OpenWrt

on: 
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: vm tools
      run: |
        tar -zxvf VMwareTools.tar.gz
        cd vmware-tools-distrib
        echo 'y' | sudo ./vmware-install.pl
    - name: Installation depends
      run: |
        sudo chmod 777 -R .
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git sed libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
    - name: Generate config file
      run: |
        cd lede
        rm -rf .config*

        echo 'src-git lienol https://github.com/Lienol/openwrt-package.git' >> feeds.conf.default

        mv ../custom ./package/

        ./scripts/feeds update -a
        ./scripts/feeds install -a

        mv ../.config_r2s_sd_8G ./.config
        make defconfig
        
        cat .config
        
    - name: Set Source
      run: |
        cat>lede/package/base-files/files/etc/banner<<EOF
          ___ ___  __      __  __________.____    _____.___.
         /   |   \/  \    /  \ \______   \    |   \__  |   |
        /    ~    \   \/\/   /  |       _/    |    /   |   |
        \    Y    /\        /   |    |   \    |___ \____   |
         \___|_  /  \__/\  /    |____|_  /_______ \/ ______|
               \/        \/            \/        \/\/       
         -----------------------------------------------------
         %D %V, %C
         -----------------------------------------------------
        EOF
        sed -i 's#^[ \t]\{0,7\}##g' lede/package/base-files/files/etc/banner
        sed -i '9s#"eth1" "eth0"#"eth0" "ech1"#g' lede/target/linux/rockchip/armv8/base-files/etc/board.d/02_network
        sed -i "16i export PS1='[\[\033[35;1m\]\u\[\033[0m\]@\[\033[34;1m\]\h\[\033\[0m\]:\[\033[32;1m\]\W\[\033[0m\] \[\033[33;1m\]\A\[\033[0m\]]\$ '" lede/package/base-files/files/etc/profile
    - name: Download package
      run: |
        cd lede && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd lede
        make -j4 V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: lede/bin
