name: Build OpenWrt

on: 
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
    - name: Installation depends
      run: |
        sudo chmod 777 -R .
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git sed libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget swig
    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede.git
    - name: Generate config file
      run: |
        cd lede
        rm -rf .config*
        mv ../.config_r2s_sd_8G ./.config
        echo 'src-git kenzo https://github.com/kenzok8/openwrt-packages' >> feeds.conf.default
        echo 'src-git small https://github.com/kenzok8/small' >> feeds.conf.default
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        cd target/linux/rockchip/armv8/base-files/etc/board.d
        sed -i '9s#"eth1" "eth0"#"eth0" "ech1"#g' 02_network
        cat 02_network
    - name: Download package
      run: |
        cd lede && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build
      run: |
        cd lede
        make -j4 V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: lede/bin
